name: xhs
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  get: ^4.6.5 
  get_storage: ^2.1.1 
  json_annotation: ^4.8.0 
  easy_refresh: ^3.3.2+1 
  bot_toast: ^4.0.4 
  card_swiper: ^3.0.1 
  video_player: ^2.7.0 
  flutter_screenutil: ^5.8.4
  firebase_core: ^2.24.2
  firebase_auth: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
   - assets/images/
  