// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy5RTH5yRQ24embbvVAfPqI54uiEAHtPY',
    appId: '1:388992575310:web:9a93767b5c20f822f1e01f',
    messagingSenderId: '388992575310',
    projectId: 'xhsf-d73ec',
    authDomain: 'xhsf-d73ec.firebaseapp.com',
    storageBucket: 'xhsf-d73ec.appspot.com',
    measurementId: 'G-3V7NJSC9HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAQaxWmcbqPNzLROwooMzoDyqOh_uJM2s',
    appId: '1:388992575310:android:82e8edd3ecc10632f1e01f',
    messagingSenderId: '388992575310',
    projectId: 'xhsf-d73ec',
    storageBucket: 'xhsf-d73ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2cmDBpqsnz37Yi7uqKOtVLiZWBS6Z9BE',
    appId: '1:388992575310:ios:01f92fc3a1e74206f1e01f',
    messagingSenderId: '388992575310',
    projectId: 'xhsf-d73ec',
    storageBucket: 'xhsf-d73ec.appspot.com',
    iosBundleId: 'com.huangweilong.flutterXhs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2cmDBpqsnz37Yi7uqKOtVLiZWBS6Z9BE',
    appId: '1:388992575310:ios:b2886ca75ad7d543f1e01f',
    messagingSenderId: '388992575310',
    projectId: 'xhsf-d73ec',
    storageBucket: 'xhsf-d73ec.appspot.com',
    iosBundleId: 'com.huangweilong.flutterXhs.RunnerTests',
  );
}
