// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3E4p56aamFkyUY8hk4jy3ThVEgnl346Y',
    appId: '1:796910062834:web:0b074963379ae122aa146b',
    messagingSenderId: '796910062834',
    projectId: 'xhs1-b4cdf',
    authDomain: 'xhs1-b4cdf.firebaseapp.com',
    databaseURL: 'https://xhs1-b4cdf-default-rtdb.firebaseio.com',
    storageBucket: 'xhs1-b4cdf.appspot.com',
    measurementId: 'G-TJ6DYE2QMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBACnNDqdWzutpLYQGcDI7RM8SypOC7Gvw',
    appId: '1:796910062834:android:8d8612bd5aee62b1aa146b',
    messagingSenderId: '796910062834',
    projectId: 'xhs1-b4cdf',
    databaseURL: 'https://xhs1-b4cdf-default-rtdb.firebaseio.com',
    storageBucket: 'xhs1-b4cdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7ajdSHkEmgv7UOF0IHWTYrnR-K5_n1-4',
    appId: '1:796910062834:ios:bd83b7d543756c21aa146b',
    messagingSenderId: '796910062834',
    projectId: 'xhs1-b4cdf',
    databaseURL: 'https://xhs1-b4cdf-default-rtdb.firebaseio.com',
    storageBucket: 'xhs1-b4cdf.appspot.com',
    iosClientId: '796910062834-jp25mkmk3t69optqm9lpr8i6ut8tjfru.apps.googleusercontent.com',
    iosBundleId: 'com.example.xhs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7ajdSHkEmgv7UOF0IHWTYrnR-K5_n1-4',
    appId: '1:796910062834:ios:0b348a0a3ddc4f31aa146b',
    messagingSenderId: '796910062834',
    projectId: 'xhs1-b4cdf',
    databaseURL: 'https://xhs1-b4cdf-default-rtdb.firebaseio.com',
    storageBucket: 'xhs1-b4cdf.appspot.com',
    iosClientId: '796910062834-vhi84brba7bejj0ek3j50115fi513mfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.xhs.RunnerTests',
  );
}
